# test

name: 签到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 0,2 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 安装Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
    - name: 安装ChromeDriver
      run: |
        pip install -r requirements.txt
        wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
    - name: 签到
      run: |
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        sckey='${{ secrets.SCKEY }}'
        
        user_list=()
        pwd_list=()
        sckey_list=()

        IFS="#"

        for u in ${user[*]}
        do
        user_list[${#user_list[*]}]=${u}
        done

        for p in ${pwd[*]}
        do
        pwd_list[${#pwd_list[*]}]=${p}
        done
        
        for s in ${sckey[*]}
        do
        sckey_list[${#sckey_list[*]}]=${s}
        done
        
        user_num=${#user_list[*]}
        pwd_num=${#pwd_list[*]}

        if [ $user_num != $pwd_num ];then
        echo "账号和密码个数不对应"
        exit 1
        else
        echo "共有 $user_num 个账号，即将开始签到"
        fi

        for ((i=0;i<$user_num;i++))
        do
        python3 checkin.py <<EOF
        ${sckey_list[$i]}
        ${user_list[$i]}
        ${pwd_list[$i]}
        EOF
        done

